services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: tcc
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p12345"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: .
    restart: unless-stopped
    ports:
      - "3005:3004"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

    # MODO DEV: monta seu c√≥digo do Windows dentro do container
    volumes:
      - ./:/user/app
      - /user/app/node_modules

    # MODO DEV: roda nodemon
    command: npm run dev

    # Ajuda o watch funcionar melhor no Docker Desktop/Windows
    environment:
      CHOKIDAR_USEPOLLING: "true"

volumes:
  mysql_data: